#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#eslint --fix ./src --ext .vue,.js,.ts
npx lint-staged
# 当我们执行 git commit -m "xxx" 时，会先对 src 目录下所有的 .vue、.js、.ts 文件执行 eslint --fix 命令，如果 ESLint 通过，成功 commit，否则终止 commit
